# Generated by Django 3.1.4 on 2022-06-28 20:51

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypage',
            name='content',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(class_name='border-traffic-lanes', max_length=255))], class_name='full')), ('subheading', wagtail.blocks.CharBlock(class_name='full')), ('paragraph', wagtail.blocks.RichTextBlock()), ('html', wagtail.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('text_with_heading', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(class_name='border-traffic-lanes', max_length=255)), ('text', wagtail.blocks.TextBlock())], class_name='full')), ('text_with_heading_and_right_image', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(class_name='border-traffic-lanes', max_length=255)), ('text', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], class_name='full')), ('text_with_heading_and_left_image', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(class_name='border-traffic-lanes', max_length=255)), ('text', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], class_name='full')), ('right_image_left_text', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.TextBlock())], class_name='full')), ('left_image_right_text', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.TextBlock())], class_name='full')), ('left_quote_right_image', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock()), ('byline', wagtail.blocks.CharBlock(max_length=255)), ('image', wagtail.images.blocks.ImageChooserBlock())], class_name='full')), ('video_embed', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=False)), ('border', wagtail.blocks.CharBlock(max_length=20, required=False)), ('embed', wagtail.blocks.CharBlock(help_text='Youtube ID only, example: WGNKjQGYIpg', max_length=20, verbose_name='Youtube Video ID'))], class_name='full')), ('table', wagtail.contrib.table_block.blocks.TableBlock(class_name='full'))], blank=True, null=True),
        ),
    ]
