# Generated by Django 3.1.4 on 2023-03-15 20:36

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0002_entrypage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(class_name='heading-blog', max_length=255))], class_name='full')), ('subheading', wagtail.core.blocks.CharBlock(class_name='full')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('text_with_heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(class_name='heading-blog', max_length=255)), ('text', wagtail.core.blocks.TextBlock())], class_name='full')), ('text_with_heading_and_right_image', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(class_name='heading-blog', max_length=255)), ('text', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], class_name='full')), ('text_with_heading_and_left_image', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(class_name='blog', max_length=255)), ('text', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], class_name='full')), ('right_image_left_text', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.TextBlock())], class_name='full')), ('left_image_right_text', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.TextBlock())], class_name='full')), ('left_quote_right_image', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock()), ('byline', wagtail.core.blocks.CharBlock(max_length=255)), ('image', wagtail.images.blocks.ImageChooserBlock())], class_name='full')), ('video_embed', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('border', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('embed', wagtail.core.blocks.CharBlock(help_text='Youtube ID only, example: WGNKjQGYIpg', max_length=20, verbose_name='Youtube Video ID'))], class_name='full')), ('table', wagtail.contrib.table_block.blocks.TableBlock(class_name='full')), ('code_block', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('Python', 'python'), ('Markup', 'html'), ('CSS', 'css'), ('Clojure', 'clojure'), ('Bash', 'shell'), ('Django', 'django'), ('Jinja2', 'jinja2'), ('Docker', 'dockerfile'), ('Git', 'git'), ('GraphQL', 'graphql'), ('Handlebars', 'handlebars'), ('.ignore', 'gitignore'), ('JSON', 'json'), ('JSON5', 'json5'), ('Markdown', 'md'), ('Markdown', 'md'), ('React JSX', 'jsx'), ('React TSX', 'tsx'), ('SASS', 'sass'), ('SCSS', 'scss'), ('TypeScript', 'ts'), ('vim', 'vim')])), ('caption', wagtail.core.blocks.CharBlock(blank=True, max_length=255)), ('page', wagtail.core.blocks.CharBlock(blank=True, max_length=255)), ('code', wagtail.core.blocks.TextBlock(blank=True, max_length=1000))], class_name='full'))], blank=True, null=True),
        ),
    ]
