# Generated by Django 3.1.4 on 2024-01-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0003_auto_20230315_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypage',
            name='this_week',
            field=models.BooleanField(default=False),
        ),
    ]
