# Generated by Django 5.0.6 on 2024-07-04 07:54

import django.db.models.deletion
import puput.fields
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmarkdown.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0004_entrypage_this_week'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypage',
            name='markdown_body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, verbose_name='body (Markdown)'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='main_color',
            field=puput.fields.ColorField(default='#4D6AE0', max_length=255, verbose_name='Blog Main Color'),
        ),
        migrations.AlterField(
            model_name='entrypage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='entrypage',
            name='content',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(class_name='heading-blog', max_length=255))], class_name='full')), ('subheading', wagtail.blocks.CharBlock(class_name='full')), ('paragraph', wagtail.blocks.RichTextBlock()), ('html', wagtail.blocks.RawHTMLBlock(icon='code', label='Raw HTML')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('text_with_heading', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(class_name='heading-blog', max_length=255)), ('text', wagtail.blocks.TextBlock())], class_name='full')), ('text_with_heading_and_right_image', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(class_name='heading-blog', max_length=255)), ('text', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], class_name='full')), ('text_with_heading_and_left_image', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(class_name='blog', max_length=255)), ('text', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], class_name='full')), ('right_image_left_text', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.TextBlock())], class_name='full')), ('left_image_right_text', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.TextBlock())], class_name='full')), ('left_quote_right_image', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock()), ('byline', wagtail.blocks.CharBlock(max_length=255)), ('image', wagtail.images.blocks.ImageChooserBlock())], class_name='full')), ('video_embed', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=False)), ('border', wagtail.blocks.CharBlock(max_length=20, required=False)), ('embed', wagtail.blocks.CharBlock(help_text='Youtube ID only, example: WGNKjQGYIpg', max_length=20, verbose_name='Youtube Video ID'))], class_name='full')), ('table', wagtail.contrib.table_block.blocks.TableBlock(class_name='full')), ('code_block', wagtail.blocks.StructBlock([('language', wagtail.blocks.ChoiceBlock(choices=[('Python', 'python'), ('Markup', 'html'), ('CSS', 'css'), ('Clojure', 'clojure'), ('Bash', 'shell'), ('Django', 'django'), ('Jinja2', 'jinja2'), ('Docker', 'dockerfile'), ('Git', 'git'), ('GraphQL', 'graphql'), ('Handlebars', 'handlebars'), ('.ignore', 'gitignore'), ('JSON', 'json'), ('JSON5', 'json5'), ('Markdown', 'md'), ('Markdown', 'md'), ('React JSX', 'jsx'), ('React TSX', 'tsx'), ('SASS', 'sass'), ('SCSS', 'scss'), ('TypeScript', 'ts'), ('vim', 'vim')])), ('caption', wagtail.blocks.CharBlock(blank=True, max_length=255)), ('page', wagtail.blocks.CharBlock(blank=True, max_length=255)), ('code', wagtail.blocks.TextBlock(blank=True, max_length=1000))], class_name='full'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='tagentrypage',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
