# Generated by Django 3.1.4 on 2021-05-01 05:41

from django.db import migrations
import home.models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_generalpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpagegalleryimage',
            name='page',
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=255))], class_name='full')), ('subheading', wagtail.core.blocks.CharBlock(class_name='full')), ('paragraph', wagtail.core.blocks.RichTextBlock(class_name='full')), ('HTML', wagtail.core.blocks.RawHTMLBlock(class_name='full')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('text_with_heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=255))], class_name='full')), ('text_heading_image', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=255)), ('text', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], class_name='full')), ('video_embed', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=255)), ('text', wagtail.core.blocks.TextBlock())], class_name='full')), ('table', wagtail.contrib.table_block.blocks.TableBlock(class_name='full')), ('code_block', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('Python', 'python'), ('Markup', 'html'), ('CSS', 'css'), ('Clojure', 'clojure'), ('Bash', 'shell'), ('Django', 'django'), ('Jinja2', 'jinja2'), ('Docker', 'dockerfile'), ('Git', 'git'), ('GraphQL', 'graphql'), ('Handlebars', 'handlebars'), ('.ignore', 'gitignore'), ('JSON', 'json'), ('JSON5', 'json5'), ('Markdown', 'md'), ('Markdown', 'md'), ('React JSX', 'jsx'), ('React TSX', 'tsx'), ('SASS', 'sass'), ('SCSS', 'scss'), ('TypeScript', 'ts'), ('vim', 'vim')])), ('caption', wagtail.core.blocks.CharBlock(blank=True, max_length=255)), ('page', wagtail.core.blocks.CharBlock(blank=True, max_length=255)), ('code', wagtail.core.blocks.TextBlock(blank=True, max_length=1000))], class_name='full')), ('quote_block', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(max_length=255)), ('attribution', wagtail.core.blocks.CharBlock(max_length=255))], class_name='full')), ('gallery_chooser', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255)), ('gallery', wagtail.snippets.blocks.SnippetChooserBlock(home.models.GeneralPageGalleryImage))], class_name='full'))], blank=True, null=True),
        ),
    ]
