# Generated by Django 3.1.4 on 2021-05-02 18:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0009_auto_20210501_0541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalpagegalleryimage',
            options={'verbose_name': 'Gallery Page Image'},
        ),
        migrations.RemoveField(
            model_name='generalpagegalleryimage',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=255))], class_name='full')), ('subheading', wagtail.blocks.CharBlock(class_name='full')), ('paragraph', wagtail.blocks.RichTextBlock(class_name='full')), ('HTML', wagtail.blocks.RawHTMLBlock(class_name='full')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('text_with_heading', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=255))], class_name='full')), ('text_heading_image', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=255)), ('text', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], class_name='full')), ('video_embed', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=255)), ('text', wagtail.blocks.TextBlock())], class_name='full')), ('table', wagtail.contrib.table_block.blocks.TableBlock(class_name='full')), ('code_block', wagtail.blocks.StructBlock([('language', wagtail.blocks.ChoiceBlock(choices=[('Python', 'python'), ('Markup', 'html'), ('CSS', 'css'), ('Clojure', 'clojure'), ('Bash', 'shell'), ('Django', 'django'), ('Jinja2', 'jinja2'), ('Docker', 'dockerfile'), ('Git', 'git'), ('GraphQL', 'graphql'), ('Handlebars', 'handlebars'), ('.ignore', 'gitignore'), ('JSON', 'json'), ('JSON5', 'json5'), ('Markdown', 'md'), ('Markdown', 'md'), ('React JSX', 'jsx'), ('React TSX', 'tsx'), ('SASS', 'sass'), ('SCSS', 'scss'), ('TypeScript', 'ts'), ('vim', 'vim')])), ('caption', wagtail.blocks.CharBlock(blank=True, max_length=255)), ('page', wagtail.blocks.CharBlock(blank=True, max_length=255)), ('code', wagtail.blocks.TextBlock(blank=True, max_length=1000))], class_name='full')), ('quote_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=255)), ('attribution', wagtail.blocks.CharBlock(max_length=255))], class_name='full')), ('gallery_chooser', wagtail.blocks.StructBlock([('gallery', wagtail.snippets.blocks.SnippetChooserBlock('home.GalleryBlock'))], class_name='full'))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GalleryBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('related_page', modelcluster.fields.ParentalKey(blank=True, help_text='Pick gallery images', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_carousel', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Gallery Carousel',
                'ordering': ['sort_order'],
            },
        ),
    ]
