# Generated by Django 3.1.4 on 2020-12-27 14:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('current', models.BooleanField(default=False)),
                ('is_case_study', models.BooleanField(default=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_pos', models.CharField(max_length=255)),
                ('client_link', models.URLField(max_length=255)),
                ('project_link', models.URLField(max_length=255)),
                ('source_link', models.URLField(max_length=255)),
                ('client_type', models.CharField(choices=[('FTE', 'Full Time Engineer'), ('CLIENT', 'Client')], default='FTE', max_length=10)),
                ('client_body', wagtail.core.fields.RichTextField(blank=True)),
                ('client_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
