# Generated by Django 3.1.4 on 2020-12-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentry',
            name='client_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='project_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='source_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
