# Generated by Django 3.1.4 on 2020-12-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('portfolio', '0002_auto_20201227_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='promote_client_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
