# Generated by Django 3.1.4 on 2021-01-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201227_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentry',
            name='client_type',
            field=models.CharField(choices=[('FTE', 'Full Time Engineer'), ('CLIENT', 'Client'), ('TALK', 'Conference Talk')], default='FTE', max_length=10),
        ),
    ]
