# Generated by Django 5.0.6 on 2024-07-04 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210108_2200'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliotag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
